@host = http://localhost:8080
@email = user@example.com
@password = password123
@rootFolderId = 1
@folderId = 2

### Read folder
GET {{host}}/api/folders/{{rootFolderId}}
Authorization: Basic {{email}} {{password}}
Accept: application/json

### Search readable folders
GET {{host}}/api/folders/search?q=api
Authorization: Basic {{email}} {{password}}
Accept: application/json

### Create folder
POST {{host}}/api/folders?parentId={{rootFolderId}}
Authorization: Basic {{email}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "name": "API folder"
}

### Rename folder
PATCH {{host}}/api/folders/{{folderId}}
Authorization: Basic {{email}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "name": "Renamed from API"
}

### Delete folder
DELETE {{host}}/api/folders/{{folderId}}
Authorization: Basic {{email}} {{password}}
Accept: application/json
